version: '3.0'
services:
  app:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      TYPEORM_HOST: postgres
    depends_on:
      - postgres
    networks:
      - back
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src

  postgres:
    build: ./postgres
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    restart: always
    environment:
      POSTGRES_PORT: ${TYPEORM_PORT}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - back
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

volumes:
  postgres_data:
  logs:
  src:
