version: '3.0'
services:
  app:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
